name: Create Flow for Messenger app

on:
  workflow_dispatch:
    inputs:

      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "Messenger"
        required: true
        type: string

      bundle_id:
        description: "BundleID (Optional)"
        default: "com.facebook.Messenger"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          path: main
          submodules: recursive

      - name: Hide sensitive inputs
        uses: levibostian/action-hide-sensitive-inputs@v1
        with:
          exclude_inputs: display_name,bundle_id

      - name: Download and validate IPA
        run: |
          wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/facebook.ipa

          file_type=$(file --mime-type -b ${{ github.workspace }}/facebook.ipa)

          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Install Dependencies
        run: brew install make ldid

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Download Flow for Messenger
        id: download_flow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          api_url="https://api.github.com/repos/dayanch96/Flow/releases/latest"

          # Workaround
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$api_url" > /dev/null

          response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$api_url")
          tag_name=$(echo "$response" | jq -r '.tag_name')
          deb_url=$(echo "$response" | jq -r '.assets[0].browser_download_url')

          if [[ "$deb_url" == "null" || -z "$deb_url" ]]; then
            echo "::error::Failed to get tweak URL from Github API"
            exit 1
          fi

          echo "GLOW_TAG=$tag_name" >> $GITHUB_ENV
          echo "Downloading: $deb_url"
          wget "$deb_url" --no-verbose -O ${{ github.workspace }}/flow.deb

      - name: Inject tweaks into IPA
        run: cyan -i messenger.ipa -o Flow_Messenger_${{ env.GLOW_TAG }}.ipa -uwef flow.deb -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }} -s

      - uses: softprops/action-gh-release@v2.0.1
        with:
          tag_name: flow-${{ env.GLOW_TAG }}
          name: Flow ${{ env.GLOW_TAG }}
          files: Flow_${{ env.GLOW_TAG }}.ipa
          draft: true

      - name: Output Release URL
        run: |
          echo "::notice::Release available at: https://github.com/${{ github.repository }}/releases"
